server:
  port: 8000  # 应用程序的端口号
  tomcat:
    max-swallow-size: 20MB

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: "@datasource.mysql.url@"
    username: "@datasource.mysql.username@"
    password: "@datasource.mysql.password@"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20 # 最大连接数
      minimum-idle: 10 # 最小空闲连接数
      idle-timeout: 600000 # 30秒
      connection-timeout: 30000 # 30秒
      max-lifetime: 1800000 # 30分钟
      connection-init-sql: "SELECT 1"
  main:
    lazy-initialization: false
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 20MB

clamav:
  host: "@clamav.host@"
  port: "@clamav.port@"

jwt:
  secret: "@jwt.secret@"
  expiration: 1200000
  refreshTime: 300000

logging:
  level:
    root: INFO  # 根日志级别
    com.l1Akr.mapper: DEBUG

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.l1Akr.dao

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: "@alibaba.cloud.access.key.id@"
    access-key-secret: "@alibaba.cloud.access.key.secret@"
    bucket-name: "@alibaba.cloud.bucket@"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
#  group-configs:
#    #分组名
#    - group: default
#      #按路径匹配
#      pathsToMatch: /**
#      packagesToScan: com.l1Akr.controller

knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽（如果是生产环境，需要把下面配置设置true）
  #  production: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表

#knife4j配置
#knife4j:
#  #是否启用增强设置
#  enable: true
#  #开启生产环境屏蔽
#  production: false
#  #是否启用登录认证
#  basic:
#    enable: true
#    username: admin
#    password: 123456
#  setting:
#    language: zh_cn
#    enable-version: true
#    enable-swagger-models: true
#    swagger-model-name: 用户模块
#    enable-search: true


## springdoc-openapi项目配置
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      packages-to-scan: com.xiaominfo.knife4j.demo.web
#
## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:

#    language: zh_cn